version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/eternaltools
permissions:
  - object: /usr/share/nginx
    owner: www-data
    group: www-data
    mode: 775
hooks:
  BeforeInstall:
    - location: codeDeploy/beforeInstall.sh
  AfterInstall:
    - location: codeDeploy/afterInstall.sh
